jobs:
- job: check
  pool:
    vmImage: 'ubuntu 16.04'
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain stable
      export PATH=$HOME/.cargo/bin:$PATH
      cargo check
- job: test
  dependsOn: check
  condition: succeeded()
  pool:
    vmImage: 'ubuntu 16.04'
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain stable
      export PATH=$HOME/.cargo/bin:$PATH
      cargo build
